"""add_ai_json_to_analyses

Revision ID: bf1356c80490
Revises: e99d3541bf96
Create Date: 2026-04-27 20:46:16.565769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1356c80490'
down_revision: Union[str, Sequence[str], None] = 'e99d3541bf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('ai_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'ai_json')
    # ### end Alembic commands ###
